-- CreateTable
CREATE TABLE `btcusd` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `o` INTEGER NOT NULL,
    `h` INTEGER NOT NULL,
    `l` INTEGER NOT NULL,
    `c` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
